Update analyze_codebase.yml

diff --git a/.github/workflows/analyze_codebase.yml b/.github/workflows/analyze_codebase.yml
--- a/.github/workflows/analyze_codebase.yml
+++ b/.github/workflows/analyze_codebase.yml
@@ -1,4 +1,4 @@
-name: Run Selected GTest Cases
+name: Analyze Codebase
 
 on:
   pull_request:
@@ -6,16 +6,37 @@ on:
 
 jobs:
   build-and-test:
-    runs-on: ubuntu-latest  # Use Linux as the environment
+    runs-on: ubuntu-latest  
 
     steps:
         - name: Checkout code
           uses: actions/checkout@v4
+          with:
+            fetch-depth: 0 
             
         - name: Send Diff to Backend
+          env:
+            FASTEST_SECRET_KEY: ${{ secrets.FASTEST_SECRET_KEY }}
           run: |
-            curl -X POST "https://28d9-197-133-69-11.ngrok-free.app/codebase/analyze?repo_name=${{ github.repository }}" \
-                -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0MTU2ODA2MSwianRpIjoiYThmZTZhYWUtZDMzYi00MGI5LWI3NGMtYWE2MTBkNjE4OGFiIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MywibmJmIjoxNzQxNTY4MDYxLCJjc3JmIjoiMjE1ZDczNTItZjk3MS00YTIxLThkNzAtNjk4NDZkYWUxNjdkIiwiZXhwIjoxNzQxNTY4OTYxfQ.y7RC7TkUtgnkBL6FyLAzdPP0-wqRKL1VbiWYZAQu4Q8" \
-                -H "Content-Type: application/json" \
-                -d '{
-                }'
+            set -e
+            BASE_COMMIT=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
+            HEAD_COMMIT=${{ github.event.pull_request.head.sha }}
+            REPO_NAME="${{ github.repository }}"
+            BRANCH_NAME="${{ github.head_ref }}"
+
+            response=$(curl -s -w "%{http_code}" -o response.txt -X POST "https://fastestai.tech/codebase/analyze" \
+              -H "Authorization: Bearer $FASTEST_SECRET_KEY" \
+              -H "Content-Type: application/json" \
+              -d '{
+                  "base_commit": "'$BASE_COMMIT'",
+                  "head_commit": "'$HEAD_COMMIT'",
+                  "repo_name": "'$REPO_NAME'",
+                  "branch_name": "'$BRANCH_NAME'"
+              }')
+            status_code=$(tail -c 3 <<< "$response")
+            if [ "$status_code" -ne 200 ]; then
+              echo "Request failed with status code $status_code"
+              cat response.txt
+              exit 1
+            fi
+          continue-on-error: false
